webapp/models.py
from flask_sqlalchemy import SQLAlchemy
from webapp.extensions import bcrypt, uploaded_images

from flask_login import AnonymousUserMixin
from flask import current_app

db = SQLAlchemy()

from itsdangerous import (
    TimedJSONWebSignatureSerializer as Serializer,
    BadSignature,
    SignatureExpired
    )


tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
    db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
)

roles = db.Table(
    'role_users',
    db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
    db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
)

class User(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    roles = db.relationship('Role', secondary = roles, backref=db.backref('users',lazy='dynamic'))

    def __init__(self, username):
        self.username = username

        default = Role.query.filter_by(name='default').one()
        self.roles.append(default)
    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)
    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    def is_authenticated(self):
        if isinstance(self, AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        return True

    def is_anonymous(self):
        if isinstance(self, AnonymousUserMixin):
            return True
        else:
            return False
    def get_id(self):
        return unicode(self.id)

    @staticmethod
    def verify_auth_token(token):
        s= Serializer(current_app.config['SECRET_KEY'])

        try:
            data = s.loads(token)
        except SignatureExpired:
            return None
        except BadSignature:
            return None

        user = User.query.get(data['id'])
        return user

class Post(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))
    text = db.Column(db.Text())
    publish_date = db.Column(db.DateTime())
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))
    comments = db.relationship(
        'Comment',
        backref='post',
        lazy='dynamic'
    )
    tags = db.relationship(
        'Tag',
        secondary=tags,
        backref=db.backref('posts', lazy='dynamic')
    )

    def __init__(self, title):
        self.title = title

    def __repr__(self):
        return "<Post '{}'>".format(self.title)


class Comment(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(255))
    text = db.Column(db.Text())
    date = db.Column(db.DateTime())
    post_id = db.Column(db.Integer(), db.ForeignKey('post.id'))

    def __repr__(self):
        return "<Comment '{}'>".format(self.text[:15])


class Tag(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title = db.Column(db.String(255))

    def __init__(self, title):
        self.title = title

    def __repr__(self):
        return "<Tag '{}'>".format(self.title)

class Recipie(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    title=db.Column(db.String(255))
    image = db.Column(db.String(255))
    user_id = db.Column(db.Integer(), db.ForeignKey('user.id'))

    @property
    def imagesrc(self):
        return uploaded_images.url(self.image)

    def __init__(self, title, image):
        self.title = title
        self.image= image
    def __repr__(self):
        return "<Recipie '{}'>".format(self.title)
class Role(db.Model):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __init__(self, name):
        self.name=name
    def __repr__(self):
        return '<Role {}>'.format(self.name)

webapp/forms.py
from flask_wtf import Form, RecaptchaField
from wtforms import StringField, TextAreaField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo
from webapp.models import db, Post, Tag, Comment, User, tags, Recipie
from flask_wtf.file import FileField, FileAllowed, FileRequired

class CommentForm(Form):
    name = StringField(
        'Name',
        validators=[DataRequired(), Length(max=255)]
    )
    text = TextAreaField(u'Comment', validators=[DataRequired()])

class LoginForm(Form):

    username= StringField('Username', [DataRequired(), Length(max=255)])
    password= PasswordField('Password', [DataRequired()])
    remember = BooleanField('Remember Me')
    def validate(self):
        check_validate = super(LoginForm, self).validate()

        # if our validators do not pass
        if not check_validate:
            return False

        # Does our the exist
        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append('Invalid username or password')
            return False

        # Do the passwords match
        if not user.check_password(self.password.data):
            self.username.errors.append('Invalid username or password')
            return False

        return True

class RegisterForm(Form):
    username = StringField('Username', [DataRequired(), Length(max=255)])
    password = PasswordField('Password', [DataRequired(), Length(min=8)])
    confirm = PasswordField('Confirm Password', [DataRequired(), EqualTo('password')])
    recaptcha= RecaptchaField()

    def validate(self):
        check_validate = super(RegisterForm, self).validate()

        if not check_validate:
            return False
        user = User.query.filter_by(username=self.username.data).first()

        if user:
            self.username.errors.append(
            "User with that name already exists"
            )
            return False
        return True

class PostForm(Form):
    title = StringField('Title', [DataRequired(), Length(max=255)])
    text = TextAreaField('Content', [DataRequired()])

class RecipieForm(Form):
    title = StringField('Title',validators=[DataRequired(), Length(max=255)])
    image = FileField('Image', validators=[DataRequired(), FileAllowed(['jpg', 'png'], 'Images only!')])

webapp/__init__.py
from flask import Flask, render_template, url_for, redirect, session
#from models import db
from .controllers.main import main_blueprint

from .config import DevConfig


def create_app(object_name):

    app = Flask(__name__)
    app.config.from_object(object_name)

    #db.init_app(app)


    #go from gen initialization to the specific bluepint
    @app.route('/')
    def index():
        return redirect(url_for('main.home'))

    app.register_blueprint(main_blueprint)

    return app

if __name__ == '__main__':
    app.run()

webapp/controllers/main.py
import datetime
from os import path
from sqlalchemy import func
from flask import render_template, Blueprint, redirect, url_for, flash, request, session, abort

#from webapp.models import db, Post, Tag, Comment, User, tags, Recipie
#from webapp.forms import CommentForm, RegisterForm, LoginForm, RecipieForm
#from webapp.extensions import facebook, login_manager, admin_permission, poster_permission
from flask_login import login_required, login_user, logout_user, current_user, current_app
from flask_principal import Identity, AnonymousIdentity, identity_changed, Permission, UserNeed

from werkzeug import secure_filename


main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder = '../templates/main'
    )

@main_blueprint.route('/index')
def home():
    return render_template('main/base.html')

@main_blueprint.route('/times')


def times():
    return render_template('main/halachiktimes.html')

@main_blueprint.route('/recipies',  methods=["GET","POST"])

def recipie():
    
    return render_template('main/recipie.html')

@main_blueprint.route('/popup')
def breaks():
    return render_template('main/about_take_breaks.html')


@main_blueprint.route('/facebook')
def facebook_login():
    return facebook.authorize(
        callback=url_for(
            '.facebook_authorized',
            next=request.referrer or None,
            _external=True
        )
    )

webapp/controllers/rest/auth.py
from flask import abort, current_app
from flask_restful import Resource
from webapp.models import User
from .parsers import user_post_parser
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer

class AuthApi(Resource):
    def post(self):
        args = user_post_parser.parse_args()
        user = User.query.filter_by(
            username=args['username']
        ).one()

        if user.check_password(args['password']):
            s = Serializer(
                current_app.config['SECRET_KEY'],
                expires_in=600
            )
            return {"token": s.dumps({'id': user.id})}
        else:
            abort(401)

webapp/templates/main/about_take_breaks.html
{% extends "main/base.html" %}

{%block head %}
    <script src='https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.2/js/tether.min.js'></script>

    <style>

    #countdown {
    color: #1B232F;
    font-family: Verdana, Arial, sans-serif;
    font-size: 30px;
    font-weight: bold;
    text-decoration: none;
}
    </style>
{% endblock %}




  {%block body%}
  <!--JumboTron!-->
<div class="jumbotron vertical-center text-xs-center">

    <h1 class="display-3" style="color:white;">The "Take a Break" WebApp</h1>
  <p style="color:white;font-size:24px">Pops up every 20 minutes to tell you take a break, click the thank you button and you start a clock, Get Up and Look Away from The Computer! </p>
</div>


<!---Card with Basic Feature-->


<div class="card">
  <div class="card-block text-xs-center">
    <h4 class="card-title">Snap Shot of 'Take A Break!'</h4>
    <h6 class="card-subtitle text-muted">Press Button below for live example</h6>
      <img src="static/images/modalsnap.JPG" alt="Card image">
  </div>

  <div class="card-block text-xs-center">
    <p class="card-text">A 5 minute timer will count down for you when hitting the right button</p>
    <input class="btn btn-primary" type="button" value = "Modal Example" onclick ="pictureLoad()">
  </div>
</div>


     <div class="modal fade" id="natureModal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Take a Break!</h4>
      </div>
      <div class="modal-body">
       <p id="bodyModal"></p>
          <div id="countdown"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="stopClock()">Stop with the Reminders</button>
        <button type="button" class="btn btn-primary" onclick="countdown( 'countdown', 5, 0 )" >Thanks! i'll take a break now, start the clock!</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
       {%endblock%}

       {%block js%}
        <script>

        var arrayIMG = new Array();
        arrayIMG[0]="space.jpg";
        arrayIMG[1]="splash.jpg";
        arrayIMG[2]="lawbook2.jpg";
        arrayIMG[3]="mountain.jpg";
        arrayIMG[4]="nature2.jpg";
        arrayIMG[5]="night.jpg";



        function natureBreak(imgAr, path){

                path = path || 'static/images/nature/'
                var num = Math.floor(Math.random()*imgAr.length);
                var img = imgAr[num];
               return '<img class="img-fluid" src="' +path +img +'" alt ="">';

        };


        var clock = setInterval(function(){pictureLoad()},1.2e6);


        function pictureLoad(){
            clearInterval(clock);
            var imgStr = natureBreak(arrayIMG,"");
            $("#bodyModal").html(imgStr);
            $("#natureModal").modal()
            //console.log("success!")

        };


function stopClock(){

            clearInterval(clock);
        }

function countdown( elementName, minutes, seconds )
{

    var element, endTime, hours, mins, msLeft, time;

    function twoDigits( n )
    {
        return (n <= 9 ? "0" + n : n);
    }

    function updateTimer()
    {
        msLeft = endTime - (+new Date);
        if ( msLeft < 1000 ) {
            $("#natureModal").modal("toggle");
        } else {
            time = new Date( msLeft );
            hours = time.getUTCHours();
            mins = time.getUTCMinutes();
            element.innerHTML = (hours ? hours + ':' + twoDigits( mins ) : mins) + ':' + twoDigits( time.getUTCSeconds() );
            setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
        }
    }

    element = document.getElementById( elementName );
    endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
    updateTimer();
}


        </script>
      {%endblock%}

webapp/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!--compatability-->
{%block head%}{%endblock%}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  <!--Font Awesome for Icons-->
    <script src="https://use.fontawesome.com/bab24acec7.js"></script>
    <style>
        #recipieHead{

           position: absolute;
            top:15px;
        }

        .jumbotron{

            background-image: url(static/images/nature/sky2.jpg);
            background-size: 100% 100%;

        }

        .vertical-center{

            text-align: center;
        }
        #headShot{

            width:250px;
          }

    </style>
      <title> {% block title%} Michelson {% endblock %} </title>

    </head>


<body>
<!--facebook login thingie - javascript-->


<!--NavBar + Collapse Content-->
<div class="collapse" id="profilePic">
    <div class="bg-inverse p-a-1">

        <h4>Aaron Michelson</h4>
        <div class="row" >
            <img class="col-sm-6" id="headShot" src="static/images/wedding%20shot.JPG">
            <span >The Author lives in Bronx,NY with his wife. He is just psyched to be afforded the opportunity to be getting his PhD at Columbia University.
            Aaron holds a Master's Degree in Material Science and Engineering from Stanford University</span>
          </br></br>
    
        </div>

    </div>
</div>
<div class="container-fluid">
 <div class='row'>

     <button class="navbar-toggler col-sm-1" type="button" data-toggle="collapse"  data-target="#profilePic">
      &#9776; </button>

      <ul class="nav nav-pills col-sm-6">
    <li class=" nav-item"><a class="nav-link active" href="{{url_for('main.home')}}">Home</a></li>

     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Apps</a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="{{url_for('main.times')}}">Shabbos Times</a>
          <a class="dropdown-item" href="{{url_for('main.recipie')}}">Recipes</a>
          <a class="dropdown-item" href="#">Mitzvos-Project</a>
          <a class="dropdown-item" href="#">Python Apps</a>
          <a class="dropdown-item" href="{{url_for('main.breaks')}}">Take a Break</a>
        </div>
      </li>
    <li class="nav-item"><a class="nav-link" href="#" data-toggle="pill">Projects</a></li>
    <li class="nav-item"><a class="nav-link" href="#" data-toggle="pill">Portfolio</a></li>
  </ul>

    </div>
    </div>
<!--JumboTron!-->
{%block messages%}

{% with messages = get_flashed_messages(with_categories=true)%}
 {% if messages %}
  {% for category, message in messages %}
    <div class="alert alert-{{category}} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span></button>
      {{message}}
    </div>
  {% endfor %}
 {% endif %}
{% endwith %}


{%endblock%}

{% block body %}
<div class="jumbotron vertical-center">

    <h1 class="display-3 text-primary">Welcome to Aaron Michelson's Space</h1>
  <p class="lead">Exploring Material Science, Science Fiction, Projects and Recipies!</p>
</div>


    <!--Modal-->

    <div class="modal fade" id="natureModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
       <p id="bodyModal"></p>
          <div id="countdown"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="stopClock()">Stop with the Reminders</button>
        <button type="button" class="btn btn-primary" onclick="countdown( 'countdown', 5, 0 )" >Thanks! i'll take a break now, start the clock!</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<!--Cards-->

<div class="container">

    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="static/images/FCC%20cell.JPG" >

                <div class="card-block text-xs-center">
                    <h4 class="card-title">Crystallography</h4>
                    <a href="https://drive.google.com/open?id=1jYS702ZGV9rUEfYjjYW7hvDZjyrfZA9QFLzi8jyAK34" class="btn btn-primary">Let's Get Started!</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="static/images/fft.jpg" >

                <div class="card-block text-xs-center">
                    <h4 class="card-title ">T.E.M</h4>
                    <a href="https://docs.google.com/presentation/d/1rCbYp4Sfm-KF-pJaXVJLR0yH8UuWFtCuUtx4bV2WFso/edit?usp=sharing" class="btn btn-primary">Let's Get Started!</a>
                </div>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="static/images/Chemistry.jpg" >

                <div class="card-block text-xs-center">
                    <h4 class="card-title">Chemistry</h4>
                    <a href="https://drive.google.com/open?id=1eviCDmB009KK1RO6Uk72ljfr8pZhvBkVw9tW9wIQrMs" class="btn btn-primary">Let's Get Started!</a>
                </div>
            </div>
        </div>

    </div>
    <div class="row">
        <div class="col-sm-4">
            <div class="card">
                <img class="card-img-top img-fluid" src="https://tc6ebq.dm2302.livefilestore.com/y3mc7oNEIGGiLTGwhI2Hb5rsYq3znEyE9hmOTyEOWCHiBf-9LNoDuUBPcFQbg3UrZpjezXnECezYY2vIHbJoOtSMdJqrIG2wg8zWKb6Loqag-wz-WTwdKrkKyaqGdNbj6qq2VA4OhkdQIX3SmdrwqbYUeb43E-HnqVKWncoYjl0dEU?width=2448&height=3264&cropmode=none"  >

                <div class="card-block text-xs-center">
                    <h4 class="card-title">Recipes</h4>
                    <a href="{{url_for('main.recipie')}}" class="btn btn-primary">Let's Get Started!</a>
                </div>
            </div>
        </div>

    </div>

  </div>
{%endblock%}

    <!-- jQuery first, then Bootstrap JS. Jqeuery and Other Stuff we need like "Tether" -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>

    <!--fade alerts-->
    <script>

  $(document).ready (function(){
   $(".alert").fadeTo(2000, 500).slideUp(500, function(){
               $(".alert").alert('close');
                });
            });
     </script>
{%block js%}
<script>
   $('#scrollParagraph').scrollspy({ target: '.navbar' });
</script>
<script src="static/javascript/take_breaks.js"></script>
{%endblock%}
    <!--Java Starts Here-->




</body>
</html>

webapp/templates/main/halachiktimes.html
{% extends "main/base.html" %}
<!--JumboTron!-->
{%block body%}
<div class="jumbotron vertical-center">

    <h1 class="display-3 text-primary">Shabbos/WeekDay Zmanim</h1>
  <p class="lead">Exploring Material Science, Science Fiction, Projects and Recipies!</p>
</div>

<div class="container" style="margin:10px;height:100%;">
  <!-- start feedwind code --><script type="text/javascript">document.write('\x3Cscript type="text/javascript" src="' + ('https:' == document.location.protocol ? 'https://' : 'http://') + 'feed.mikle.com/js/rssmikle.js">\x3C/script>');</script><script type="text/javascript">(function() {var params = {rssmikle_url: "http://www.chabad.org/tools/rss/zmanim.xml?locationId=10461&locationType=2",rssmikle_frame_width: "300",rssmikle_frame_height: "500",frame_height_by_article: "0",rssmikle_target: "_blank",rssmikle_font: "Arial, Helvetica, sans-serif",rssmikle_font_size: "15",rssmikle_border: "off",responsive: "on",rssmikle_css_url: "",text_align: "left",text_align2: "left",corner: "off",scrollbar: "on",autoscroll: "off",scrolldirection: "up",scrollstep: "3",mcspeed: "20",sort: "Off",rssmikle_title: "on",rssmikle_title_sentence: "",rssmikle_title_link: "",rssmikle_title_bgcolor: "#0066FF",rssmikle_title_color: "#FFFFFF",rssmikle_title_bgimage: "",rssmikle_item_bgcolor: "#FFFFFF",rssmikle_item_bgimage: "",rssmikle_item_title_length: "55",rssmikle_item_title_color: "#0066FF",rssmikle_item_border_bottom: "on",rssmikle_item_description: "on",item_link: "off",rssmikle_item_description_length: "150",rssmikle_item_description_color: "#666666",rssmikle_item_date: "gl1",rssmikle_timezone: "Etc/GMT",datetime_format: "%b %e, %Y %l:%M %p",item_description_style: "html",item_thumbnail: "full",item_thumbnail_selection: "auto",article_num: "15",rssmikle_item_podcast: "off",keyword_inc: "",keyword_exc: ""};feedwind_show_widget_iframe(params);})();</script><div style="font-size:10px; text-align:center; width:500px;"><a href="http://feed.mikle.com/" target="_blank" style="color:#CCCCCC;">RSS Feed Widget</a><!--Please display the above link in your web page according to Terms of Service.--></div><!--  end  feedwind code -->

</div> <!--closing container with feed tag-->
{%endblock%}
     <!-- jQuery first, then Bootstrap JS. Jqeuery and Other Stuff we need like "Tether" -->

  {%block js%}
 <script src='https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.2/js/tether.min.js'></script>
  {%endblock%}

webapp/templates/main/login.html
{% extends "main/base.html" %}

{%block body%}
<div class="container-fluid">
<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    {%if current_user == True %}
      <h2> Please logout before logging into a different account </h2>
      <a class="btn btn-primary" href="{{url_for('.logout')}}">Logout</a>
    {%else%}
        <h2>Login </h2>
      <h6 class="text-muted"> Please log in to access features such as Recipies and Class Notes (I just like knowing who stopped by in the neighborhood) </h6>
      </br>
      <form class="form-group form-inline" method="POST" action="{{url_for('.login')}}" style="background-color:#EBEBEB; border-radius:5px; margin:20px;padding:20px;">
        {{form.hidden_tag()}}
        <h4>Login:</h4>
        {% from "_formhelper.html" import render_form %}
          {{render_form(form.username, class='form-control', placeholder="Username")}}
          {{render_form(form.password, class='form-control', placeholder="Password")}}
          {{render_form(form.remember, class='form-control')}}
        <input class="btn btn-primary form-control" type="submit" value="Login">
      </form>
      </br>

      <h4 class="text-center">Login/Register With Facebook</h4>
      <a class="btn btn-primary" href="{{url_for('.facebook_login')}}">Login via Facebook</a>
    </div>
  </div>
</div>
{%endif%}
{% endblock%}

{% block js%}
<script>
  function onSignIn(googleUser) {
    // Useful data for your client-side scripts:
    var profile = googleUser.getBasicProfile();
    console.log("ID: " + profile.getId()); // Don't send this directly to your server!
    console.log('Full Name: ' + profile.getName());
    console.log('Given Name: ' + profile.getGivenName());
    console.log('Family Name: ' + profile.getFamilyName());
    console.log("Image URL: " + profile.getImageUrl());
    console.log("Email: " + profile.getEmail());

    // The ID token you need to pass to your backend:
    var id_token = googleUser.getAuthResponse().id_token;
    console.log("ID Token: " + id_token);
  };
</script>
{%endblock%}

webapp/templates/main/recipie.html
{%extends "main/base.html"%}
  <!--compatability-->
{%block head%}
<!-- Magnific Popup core CSS file -->
<link rel="stylesheet" href="static/javascript/magnific-popup/magnific-popup.css">
<script src="https://use.fontawesome.com/bab24acec7.js"></script>

{% endblock %}

{% block title %} Recipie {% endblock %}




{% block body %}

<div class="container" id="recipeHead">

    <div class="popup-gallery">



    </div>
    <a href="https://1drv.ms/a/s!AqxJG_FiqKX1htM2XWXKriLhwps85Q" title="Michelson and Family Recipies">Recipies Link
    </a>


{% endblock %}


{% block js %}
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
    <!-- Magnific Popup core JS file -->
<script src="static/javascript/magnific-popup/jquery.magnific-popup.js"></script>

    <!--Java Starts Here-->
    <script>

    //magnific initizlization
    $(document).ready(function() {
	$('.popup-gallery').magnificPopup({
		delegate: 'a',
		type: 'image',
		tLoading: 'Loading image #%curr%...',
		mainClass: 'mfp-img-mobile',
		gallery: {
			enabled: true,
			navigateByImgClick: true,
			preload: [0,1] // Will preload 0 - before current, and 1 after the current image
		},
		image: {
			tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
			titleSrc: function(item) {
				return item.el.attr('title') + '<small>by Aaron, Friends and Family</small>';
			}
		}
	});
});

    </script>


{% endblock %}

webapp/templates/main/register.html
{% extends "main/base.html" %}

{%block body%}
<div class="container">
  <div class="row">
    <div class="col-md-6">
  <h1> This is the Registration Form! </h1>
<form method="POST" action="{{url_for('.register')}}">
{{form.hidden_tag()}}
<h3>Registration:</h3>
{% from "_formhelper.html" import render_form %}
  {{render_form(form.username)}}
  {{render_form(form.password)}}
  {{render_form(form.confirm)}}
  {{render_form(form.recaptcha)}}
  <input class="btn btn-primary" type="submit" value="Submit">
</form>
</div>
</div>
</div>

{% endblock%}